### ISSUE TITLE
nextion-fw-upload with NX1060P101-011C-I and NX3224T024_011

### ISSUE THREAD

**Issue by ftfelix** [yozik04/nextion#28]
Hello, 

I succesfully updated the Nextion display NX3224T024_011 with "nextion-fw-upload". Now I want to use the bigger NX1060P101-011C-I. I can not establish an update with "nextion-fw-upload". I checked the communication from the display to the RaspberryPi. There is one short answer from the display during the initial baudrate finding procedure. I even implemented a hardware levelshifter to ensure the right logic voltages 3V3 (RaspberryPi) <-> 5V0 (NX1060P101-011).
Do you have any idea? Thank you very much.

pi@raspberrypi:~/Documents/python_projects $ nextion-fw-upload /dev/ttyS0 NX1060P101-011C-I.tft
2022-03-19 15:01:07,142 INFO     nextion.nextion.client Connecting: /dev/ttyS0, baud: 2400
2022-03-19 15:01:07,145 INFO     nextion.nextion.protocol.base Connected to serial
2022-03-19 15:01:08,942 WARNING  nextion.nextion.client No valid reply on 2400 baud. Closing connection
2022-03-19 15:01:08,943 ERROR    nextion.nextion.protocol.base Connection lost
2022-03-19 15:01:08,944 WARNING  nextion.nextion.client Baud 2400 did not work
2022-03-19 15:01:08,944 INFO     nextion.nextion.client Connecting: /dev/ttyS0, baud: 4800
2022-03-19 15:01:08,946 INFO     nextion.nextion.protocol.base Connected to serial
2022-03-19 15:01:09,910 WARNING  nextion.nextion.client No valid reply on 4800 baud. Closing connection
2022-03-19 15:01:09,912 ERROR    nextion.nextion.protocol.base Connection lost
2022-03-19 15:01:09,913 WARNING  nextion.nextion.client Baud 4800 did not work
2022-03-19 15:01:09,914 INFO     nextion.nextion.client Connecting: /dev/ttyS0, baud: 9600
2022-03-19 15:01:09,916 INFO     nextion.nextion.protocol.base Connected to serial
2022-03-19 15:01:10,463 WARNING  nextion.nextion.client No valid reply on 9600 baud. Closing connection
2022-03-19 15:01:10,464 ERROR    nextion.nextion.protocol.base Connection lost
2022-03-19 15:01:10,465 WARNING  nextion.nextion.client Baud 9600 did not work
2022-03-19 15:01:10,465 INFO     nextion.nextion.client Connecting: /dev/ttyS0, baud: 19200
2022-03-19 15:01:10,467 INFO     nextion.nextion.protocol.base Connected to serial
2022-03-19 15:01:10,802 WARNING  nextion.nextion.client No valid reply on 19200 baud. Closing connection
2022-03-19 15:01:10,803 ERROR    nextion.nextion.protocol.base Connection lost
2022-03-19 15:01:10,804 WARNING  nextion.nextion.client Baud 19200 did not work
2022-03-19 15:01:10,805 INFO     nextion.nextion.client Connecting: /dev/ttyS0, baud: 38400
2022-03-19 15:01:10,807 INFO     nextion.nextion.protocol.base Connected to serial
2022-03-19 15:01:11,037 WARNING  nextion.nextion.client No valid reply on 38400 baud. Closing connection
2022-03-19 15:01:11,038 ERROR    nextion.nextion.protocol.base Connection lost
2022-03-19 15:01:11,039 WARNING  nextion.nextion.client Baud 38400 did not work
2022-03-19 15:01:11,040 INFO     nextion.nextion.client Connecting: /dev/ttyS0, baud: 57600
2022-03-19 15:01:11,042 INFO     nextion.nextion.protocol.base Connected to serial
2022-03-19 15:01:11,238 WARNING  nextion.nextion.client No valid reply on 57600 baud. Closing connection
2022-03-19 15:01:11,239 ERROR    nextion.nextion.protocol.base Connection lost
2022-03-19 15:01:11,240 WARNING  nextion.nextion.client Baud 57600 did not work
2022-03-19 15:01:11,240 INFO     nextion.nextion.client Connecting: /dev/ttyS0, baud: 115200
2022-03-19 15:01:11,242 INFO     nextion.nextion.protocol.base Connected to serial
2022-03-19 15:01:11,405 WARNING  nextion.nextion.client No valid reply on 115200 baud. Closing connection
2022-03-19 15:01:11,406 ERROR    nextion.nextion.protocol.base Connection lost
2022-03-19 15:01:11,407 WARNING  nextion.nextion.client Baud 115200 did not work
2022-03-19 15:01:11,407 INFO     nextion.nextion.client Connecting: /dev/ttyS0, baud: 230400
2022-03-19 15:01:11,409 INFO     nextion.nextion.protocol.base Connected to serial
2022-03-19 15:01:11,554 WARNING  nextion.nextion.client No valid reply on 230400 baud. Closing connection
2022-03-19 15:01:11,556 ERROR    nextion.nextion.protocol.base Connection lost
2022-03-19 15:01:11,557 WARNING  nextion.nextion.client Baud 230400 did not work
2022-03-19 15:01:11,557 ERROR    nextion.nextion.client Connection failed
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.9/site-packages/nextion/client.py", line 159, in connect
    result = await self._try_connect_on_different_baudrates()
  File "/home/pi/.local/lib/python3.9/site-packages/nextion/client.py", line 200, in _try_connect_on_different_baudrates
    raise ConnectionFailed("No baud rate suited")
nextion.exceptions.ConnectionFailed: No baud rate suited
Traceback (most recent call last):
  File "/home/pi/.local/bin/nextion-fw-upload", line 8, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python3.9/site-packages/nextion/console_scripts/upload_firmware.py", line 48, in main
    loop.run_until_complete(upload(args))
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/pi/.local/lib/python3.9/site-packages/nextion/console_scripts/upload_firmware.py", line 11, in upload
    await nextion.connect()
  File "/home/pi/.local/lib/python3.9/site-packages/nextion/client.py", line 159, in connect
    result = await self._try_connect_on_different_baudrates()
  File "/home/pi/.local/lib/python3.9/site-packages/nextion/client.py", line 200, in _try_connect_on_different_baudrates
    raise ConnectionFailed("No baud rate suited")
nextion.exceptions.ConnectionFailed: No baud rate suited

**Comment by ftfelix** [comment]
I solved it... no enough voltage at the display...

**Comment by yozik04** [comment]
=) It is great that you have resolved it. I personally use baud 9600. It is enough speed for most of the use cases.
